apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
spec:
  selector:
    matchLabels:
      app: notification
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: renatocesarf/notification
          envFrom:
            - configMapRef:
                name: notification-configmap
            - secretRef:
                name: notification-secret
